spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=America/Asuncion

server.port=${PORT:8080}

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-minutes=${APP_JWT_EXPIRATION_MINUTES:480}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS}

app.tenancy.shared-datasource-key=shared
