spring.datasource.url=jdbc:postgresql://localhost:5432/guarani_pos
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=America/Asuncion

server.port=8080

app.jwt.secret=5Wc6ojfL6a5SEcFKW1d6G8SkVv0v6cJfV2qZP1xUqM9xP0eJxB3wQm4nY8rL7tAa
app.jwt.expiration-minutes=480
